---
name: "activate namespace"

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
    branches:
      - main
    types: [labeled]


jobs:
  activate:
    runs-on: ubuntu-latest
    steps:
      - name: activate namespace
        env:
          GH_TOKEN: ${{ github.token }}
        run: | 
          if [ "${{ github.event_name }}" == 'pull_request' ]; then
            echo "inside a pr"
            branchname=${{ github.event.pull_request.head.ref }}
          elif [[ $GITHUB_EVENT_NAME == 'push' ]]; then
            echo "inside a branch"
            branchname=${GITHUB_REF#refs/heads/}
          fi
          echo "branchname: $branchname"
          
          # gh pr view will exit with 1 when there is no pr for a given branch
          hasLabel=$(gh pr view $branchname --repo ${{ github.repository }} --json labels --jq '.labels[] | select(.name == "auto-activate-ns") | length > 0' 2>/dev/null && echo "true" || echo "false")
          
          if [ "$hasLabel" == "true" ]; then
              echo "has pr, has label, extend activation time"
          else
              echo "may have an pr, but if, there is no label, create ns if there isn't one already"
          fi