---
name: "activate namespace"

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
    branches:
      - main
    types: [labeled]


jobs:
  activate:
    runs-on: ubuntu-latest
    steps:
      - name: activate namespace
        env:
          GH_TOKEN: ${{ github.token }}
        run: | 
          if [ "${{ github.event_name }}" == 'pull_request' ]; then
            echo "inside a pr"
            branch_name=${{ github.event.pull_request.head.ref }}
          elif [[ $GITHUB_EVENT_NAME == 'push' ]]; then
            echo "inside a branch"
            branch_name=${GITHUB_REF#refs/heads/}
          fi
          echo "branch_name: $branch_name"
          
          # gh pr view will exit with 1 when there is no pr for a given branch
          pr_labels=$(gh pr view $branch_name --repo ${{ github.repository }} --json labels 2>/dev/null) && echo "$pr_labels" || echo "no pr found"
          echo "pr_labels: $pr_labels"
          has_activation_label=$(echo $pr_labels | jq '.labels[] | select(.name == "auto-extend-ns-activation-time") | length > 0')
          
          if [ "$has_activation_label" == "true" ]; then
              echo "has pr, has label, extend activation time"
              # curl -XPOST -H 'Content-Type: application/json' "https://activate.brb.dbildungscloud.dev/namespace/extendAndWait?namespace=$branch_name"
          else
              echo "may have an pr, but if, there is no label, will create initial ns entry if there isn't one already"
              # curl -XPUT -H 'Content-Type: application/json' "https://activate.brb.dbildungscloud.dev/namespace/createIfNotExistsAndWait?namespace=$branch_name"
          fi