name: Changelog

on:
  push:
    branches:
      - 'release/*'


jobs:
  changelog:
    # Only continue if the commit message has '[deploy]' in it
    name: Changelog
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create release notes (release_notes.md)
        #run: ./generate_release_notes.sh ${LATEST_TAG} origin/trunk ${GRID_VERSION} ${BUILD_DATE}
        run: 'git --no-pager log "$(git describe --tags --abbrev=0)...main" --pretty=format:"* [\`%h\`](https://github.com/Loki-Afro/manualaction/commit/%H) - %s :: %an" --reverse >> release_notes.md'
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: release_notes.md
          draft: false
          prerelease: true
