---
name: "create release on tag"

on:
  push:
    tags:
      - '[0-9]*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Docker meta Service Name
        id: docker_meta_img
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch,enable=false,priority=600
            type=sha,enable=true,priority=600,prefix=

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        if: ${{ env.IMAGE_EXISTS == 0 }}
        uses: docker/setup-buildx-action@v2

      - name: Build and push ${{ github.repository }}
        if: ${{ env.IMAGE_EXISTS == 0 }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/loki-afro/manualaction:${{ github.ref_name }}
          labels: ${{ steps.docker_meta_img.outputs.labels }}

  create-release:
    needs:
      - build_and_push
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    steps:
      - name: run trivy
        uses: aquasecurity/trivy-action@9ab158e8597f3b310480b9a69402b419bc03dbd5
        with:
          image-ref: 'ghcr.io/loki-afro/manualaction:${{ github.ref_name }}'
          output: 'dependency-results.sbom.json'
      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          body: 'refer to the schulcloud-client release notes https://github.com/hpi-schul-cloud/schulcloud-client/releases/'
          files: dependency-results.sbom.json
