on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:
    dependabot-to-jira:
        name: 'create damn ticket'
        runs-on: ubuntu-latest

        steps:
          - name: create ticket
            run: |
              curl -D- \
                -u ${{ secrets.JIRA_USER_NAME }}:${{ secrets.JIRA_USER_PASSWORD }}\
                -H "Content-Type: application/json" \
                -X POST --data '{
                     "fields": {
                       "project": {
                         "key": "BC"
                       },
                       "summary": "${{ github.event.pull_request.title }}",
                       "description": "h4. Task:
                                       ${{ github.event.pull_request.title }}
                                       ${{ github.event.pull_request.html_url }}",
                       "issuetype": {
                         "id": "10100"
                       },
                       "customfield_10004" : 231,
                       "customfield_10000": "BC-3139"
                    }
                  }' \
              'https://ticketsystem.dbildungscloud.de/rest/api/2/issue/'