---
name: "create release on tag"

on:
  pull_request:
    branches: [ main ]

jobs:
  hackhack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: do something
        run: echo "meeeeeeeeeeh $(hostname -I)"
