---
name: "hackhack"

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
    types: [labeled]

jobs:
  hackhack:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: do something
        run: | 
          echo "meeeeeeeeeeh $(hostname -I)"
          if [ "${{ secrets.TEST_SECRET }}" != '' ]; then
            echo "secret available"
          else 
            echo "secret unavailable"
          fi