---
name: "hackhack"

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
    types: [labeled]

jobs:
  hackhack-job:
    #https://github.com/actions/runner/issues/1173#issuecomment-1354501147
    if: |
      (github.actor == 'dependabot[bot]' &&
      contains(github.event.issue.labels.*.name, 'ready-for-ci') == 'true') ||
      github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: do something
        run: | 
          echo "meeeeeeeeeeh $(hostname -I)"
          if [ "${{ secrets.TEST_SECRET }}" != '' ]; then
            echo "secret available"
          else 
            echo "secret unavailable"
            exit 1
          fi